name: Run C# Unit Tests on PR

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --configuration Release --no-restore

      - name: Run Unit Tests
        run: dotnet test --configuration Release --no-build --logger trx --results-directory TestResults

      - name: Ensure TestResults Directory Exists
        run: mkdir -p TestResults

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4  # Use latest version
        with:
          name: test-results
          path: TestResults
